version: '3.3'
services:
  db:
    image: mysql:8.3.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: brs
      MYSQL_USER: brs_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - '3306:3306'
    volumes:
      - brs-db:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password

  backend:
    image: catchsudheera/brs-backend:v1.1
    container_name: backend
    restart: unless-stopped
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "8080:8080"
    secrets:
      - db_password

secrets:
  db_password:
    file: db_password
  db_root_password:
    file: db_root_password

volumes:
  brs-db: