spring:
  application:
    name: coordinator-backend
  datasource:
    url: jdbc:mysql://localhost:3306/brs
    username: brs_user
    password: password
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

aws:
  api:
    gateway:
      resource-url: https://wzn6683ql5.execute-api.eu-central-1.amazonaws.com/prod

chatbot: &commonChatBot
  id: sample-id
  token: 6991917782:AAFInVjoiLXgHaRggVKd_LFqIVOmV4rY5bI

openSlotGroup: &commonOpenSlotGroup
  groupId: -4573540198

adminGroup: &commonAdminGroup
  groupId: -4542431431

encounter-events-config:
  encounterEvents:
    - name: wednesday-badminton
      chatBot:
        <<: *commonChatBot
      memberGroup:
        groupId: -4531367864
      openSlotGroup:
        <<: *commonOpenSlotGroup
      adminGroup:
        <<: *commonAdminGroup
      cron: "0 0 * * WED"
      totalSlots: 18
    - name: monday-badminton
      chatBot:
        <<: *commonChatBot
      memberGroup:
        groupId: sample-id-2
      openSlotGroup:
        <<: *commonOpenSlotGroup
      adminGroup:
        <<: *commonAdminGroup
      cron: "0 0 * * MON"
      totalSlots: 18