---
- name: Create stack root directory
  file:
    path: "{{ brs_container_stack_location }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Create Mysql directories
  file:
    path: "{{ mysql_config_path }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Create Frontend directories
  file:
    path: "{{ frontend_config_path }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Create Frontend DB file
  file:
    path: "{{ frontend_db_file_path }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Create SWAG directories
  file:
    path: "{{ swag_config_path }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Create Mysql data directories
  file:
    path: "{{ mysql_config_path }}/var-lib-mysql"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Copy Docker compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ brs_container_stack_location }}/docker-compose.yml"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Copy SWAG certbot config for cloudflare
  template:
    src: cloudflare.ini.j2
    dest: "{{ swag_config_path }}/dns-conf/cloudflare.ini"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"
    mode: '0400'

- name: Copy nginx default config
  copy:
    src: default.conf
    dest: "{{ swag_config_path }}/nginx/site-confs/default.conf"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Copy backend container subdomain config
  copy:
    src: backend.subdomain.conf
    dest: "{{ swag_config_path }}/nginx/proxy-confs/backend.subdomain.conf"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Start Docker containers using docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ brs_container_stack_location }}"
  tags: start-stacks

- name: Adding the Systemd units for docker-compose management
  import_role:
    name: docker-compose-systemd
  vars:
    docker_compose_dir_path: "{{ brs_container_stack_location }}"
    stack_name: container-stack-brs

- name: Stop Docker containers if running
  block:
    - name: Check wether the docker file exist
      stat:
        path: "{{ brs_container_stack_location }}/docker-compose.yml"
      register: brs_container_stack_location_docker_compose_file

    - name: Check validity of compose file
      shell: "docker compose -f {{ brs_container_stack_location }}/docker-compose.yml config"
      register: brs_container_stack_docker_compose_file_validate
      ignore_errors: yes

    - name: Stopping using docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ brs_container_stack_location }}"
        state: absent
      when: brs_container_stack_location_docker_compose_file.stat.exists and brs_container_stack_docker_compose_file_validate.failed|bool != true
  tags: [ 'never', 'stop-stacks' ]