spring:
  datasource:
    url: jdbc:mysql://localhost:3306/brs
    username: brs_user
    password: zuX$Q1SmJC6v@!DO
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

host:
  frontend: http://localhost:3000

api:
  key: sample-api-key
  admin:
    emails: test@test.com, test2@test.com
  tg:
    key: sample-telegram-key
    group: sample-group-id

server:
  forward-headers-strategy: NATIVE

google:
  client:
    id: 441369635705-38lnqsu3e312hnhoa1c7eb8flogfm832.apps.googleusercontent.com