spring:
  datasource:
    url: jdbc:mysql://<hostname>:3306/brs
    username: brs_user
    password: <pw>
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl