spring:
  datasource:
    url: jdbc:mysql://localhost:3306/brs
    username: brs_user
    password: local_dev_password
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

host:
  url: http://localhost:8080

api:
  key: sample-api-key

server:
  forward-headers-strategy: NATIVE