version: '3.3'
services:
  db:
    image: mysql:8.3.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: brs
      MYSQL_USER: brs_user
      MYSQL_PASSWORD: user-password
    ports:
      - '3306:3306'
    volumes:
      - /tmp/lib/mysql:/var/lib/mysql
