name: apl-Arangorn FRONTEND Build

on: workflow_dispatch

jobs:
  push-frontend-image:
    runs-on: ubuntu-latest
    environment: production-apl-aragon-duckdns
    defaults:
      run:
        working-directory: './frontend'
    steps:
      - name: 'Checkout latest main branch'
        uses: actions/checkout@main

      - name: 'Login to ghcr'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_PUSH_TOKEN}}

      - name: 'Build and push'
        run: |
          echo $NEXT_PUBLIC_BACKEND_URL >> .env 
          docker build . --tag ghcr.io/catchsudheera/brs-frontend:v1.2
          docker push ghcr.io/catchsudheera/brs-frontend:v1.2

