name: dutchlankanshuttlemasters FRONTEND Build

on: workflow_dispatch

jobs:
  push-frontend-image:
    runs-on: ubuntu-latest
    environment: production-dutchlankanshuttlemasters
    defaults:
      run:
        working-directory: './frontend'
    steps:
      - name: 'Checkout latest main branch'
        uses: actions/checkout@main

      - name: 'Login to ghcr'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_PUSH_TOKEN}}

      - name: 'Build and push'
        run: |
          echo "NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}" >> .env.production
          echo "NEXT_PUBLIC_AUTH_ENABLED=${{ secrets.NEXT_PUBLIC_AUTH_ENABLED }}" >> .env.production
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env.production
          echo "ALLOWED_ADMIN_EMAILS=${{ secrets.ALLOWED_ADMIN_EMAILS }}" >> .env.production
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.production
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.production
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.production
          echo "NEXT_PUBLIC_BUILD_IDENTIFIER=$(TZ=Europe/Amsterdam date '+%Y-%m-%d %H:%M:%S')" >> .env.production
          docker build . --tag ghcr.io/catchsudheera/brs-frontend:v2.0
          docker push ghcr.io/catchsudheera/brs-frontend:v2.0
