name: FRONTEND Staging build

on:
  push:
    paths:
      - frontend/**

jobs:
  push-backend-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './frontend'
    steps:
      - name: 'Checkout the branch that triggered the workflow'
        uses: actions/checkout@v4

      - name: 'Set the tag name according to the branch'
        run: if [ "${GITHUB_REF##*/}" = "main" ]; then echo "TAG=rc" >> $GITHUB_ENV; else echo "TAG=staging" >> $GITHUB_ENV; fi

      - name: 'Login to ghcr'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_PUSH_TOKEN}}

      - name: 'Build and push'
        run: |
          docker build . --tag ghcr.io/catchsudheera/brs-frontend:$TAG
          docker push ghcr.io/catchsudheera/brs-frontend:$TAG

