name: [BACKEND] Build and publish images to ghcr

on: workflow_dispatch

jobs:
  push-backend-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './backend'
    steps:
      - name: 'Checkout latest main branch'
        uses: actions/checkout@main

      - name: 'Packaging environment'
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: 'Package'
        run: mvn clean install

      - name: 'Login to ghcr'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_PUSH_TOKEN}}

      - name: 'Build and push'
        run: |
          docker build . --tag ghcr.io/catchsudheera/brs-backend:v1.2
          docker push ghcr.io/catchsudheera/brs-backend:v1.2

